# In V1, order data was stored in Python dictionaries: goods, members and carts
# In V2, order data is stored permanently in MySQL tables: orders and order_items

# import the halper function, responsible for opening, 
# providing and safely closing a database connection 
# for each HTTP request
from src.models.database import get_db

# V1 reference:
# @app.route('/buy', methods=['POST'])
# def buy():
#     inputData = request.json
#     product_id = inputData.get("product_id")
#     quantity = inputData.get("quantity")
#     member_id = inputData.get("member_id")
#
#     item = goods[product_id]
#     total = item["price"] * quantity
#     member_cart = carts[member_id]
#
#     for cart_item in member_cart:
#         if cart_item["product_id"] == product_id:
#             cart_item["quantity"] += quantity
#             cart_item["total"] = cart_item["price"] * cart_item["quantity"]
#
# V2 change:
# There is no temporary Python cart anymore.
# The controller receives user_id and items from Postman,
# then this model creates a permanent order in MySQL
def create_order(user_id, items):
    # get database connection
    db = get_db()
    # create cursor - is the tool that sends SQL commands to MySQL
    cursor = db.cursor()

    # Create a temporary list for checked items.
    # We do not insert data immediately, because first we must validate all products and stock
    prepared_items = []

    # check every product before creating the order
    for item in items:
        # Get product_id from current item
        product_id = item["product_id"]
        # Get quantity from current item
        quantity = item["quantity"]

        # V1 used goods[product_id] to find a product in the goods dictionary
        # V2 uses SELECT to find the product in MySQL
        cursor.execute("SELECT * FROM products WHERE id = %s", (product_id,))
        
        # fetchone() returns one product row if it exists, 
        # otherwise it returns None
        product = cursor.fetchone()

        # If product does not exist in MySQL, stop order creation
        if not product:
            cursor.close()
            return None, "Product does not exist"

        # Check whether product stock is enough for requested quantity
        if product["stock"] < quantity:
            cursor.close()
            return None, "Not enough stock"

        # Save checked item data into prepared_items.
        # product_name and price are copied into order_items to keep receipt history stable
        prepared_items.append({
            "product_id":product_id,
            "product_name": product["name"],
            "price": product["price"],
            "quantity": quantity,
        })

    # create main order record in orders table
    # orders table stores order information of the user
    # total_amount and total_categories are calculated later when receipt is generated
    cursor.execute("INSERT INTO orders (user_id) VALUES (%s)",
        (user_id,)
    )

    # Get new order id generated by MySQL
    # This id will be used to connect order_items to this order
    order_id = cursor.lastrowid

    # save every checked product as one row in order_items table
    for item in prepared_items:
        # insert one receipt item into order_items
        cursor.execute(
            """INSERT INTO order_items
            (order_id, product_id, product_name, price, quantity)
            VALUES (%s, %s, %s, %s, %s)
            """,
            (
                order_id,
                item["product_id"],
                item["product_name"],
                item["price"],
                item["quantity"]
            )
        )

        # reduce product stock after the item is added to the order
        cursor.execute(
            """
            UPDATE products
            SET stock = stock - %s
            WHERE id = %s
            """,
            (item["quantity"], item["product_id"])
        )

    # save INSERT and UPDATE changes to MySQL.
    db.commit()
    # close cursor after all SQL commands are finished
    cursor.close()

    # return complete receipt to controller
    # controller also checks that this order belongs to this user
    return get_order_receipt(order_id, user_id), None


# V1 reference:
# @app.route('/order', methods=['GET'])
# def order():
#     member_id = request.args.get("member_id")
#     member = members[member_id]
#     member_cart = carts[member_id]
#
#     total = 0
#     for item in member_cart:
#         total += item['total']
#
#     carts[member_id] = []
#
#     return jsonify({
#         "success": True,
#         "message": "Order created successfully",
#         "customer": member,
#         "item": member_cart,
#         "total_amount": total,
#         "total_categories": fruit_types,
#         "member_id": member_id
#     })
#
# V2 change:
# Receipt is not built from carts dictionary anymore.
# It is rebuilt from orders + order_items + users tables
# user_id is passed into SQL to avoid users from reading others users' cart
def get_order_receipt(order_id, user_id):
    db = get_db()
    cursor = db.cursor()
    # select main order information and related user data.
    # JOIN is used because orders table stores only user_id,
    # while user name/email/phone/address are stored in users table
    # Where orders.id = % AND orders.user_id = % is the authorization protection
    # If the order belongs to another user, MySQL returns no row
    cursor.execute(
        """
        SELECT
            orders.id AS order_id,
            orders.user_id,
            users.name AS user_name,
            users.email,
            users.phone,
            users.address,
            orders.created_at,
            orders.paid
        FROM orders
        JOIN users ON orders.user_id = users.id
        WHERE orders.id = %s
        AND orders.user_id = %s
        """,
        (order_id, user_id)
    )

    # fetchone() returns one order receipt header, or None if order does not exist
    order = cursor.fetchone()

    # if order does not exist or doesn't belong to current user, close cursor and return None to controller
    if not order:
        cursor.close()
        return None

    # get all products inside this order
    cursor.execute(
        """SELECT
            id
            product_id,
            product_name,
            price,
            quantity
        FROM order_items
        WHERE order_id = %s
        """,
        (order_id,)
    )
    
    # fetchall() returns a list of all receipt items
    items = cursor.fetchall()

    # close cursor after reading all data
    cursor.close()

    # Calculate totals dynamically instead of storing them in database
    # This keeps orders table simpler and avoids duplicated total values
    total_amount = 0
    total_categories = 0
    for item in items:
        total_categories += 1
        item["total"] = item["price"] * item["quantity"]
        total_amount += item["total"]

    # add items list into the main order dictionary.
    # final receipt contains order info + customer info + item list
    # add calculated values into final receipt dictionary
    order["items"] = items    
    order["total_amount"] = total_amount
    order["total_categories"] = total_categories

    # return complete receipt to controller
    return order


def delete_order(order_id, user_id):
    # first check whether the order exists before deleting
    existing_order = get_order_receipt(order_id, user_id)

    # if order does not exist, return False to controller
    # controller will convert this result to 404 error response
    if not existing_order:
        return False

    db = get_db()
    cursor = db.cursor()
    # delete order from orders table by id
    cursor.execute(
        "DELETE FROM orders WHERE id = %s AND user_id = %s",
        (order_id, user_id)
    )

    # save DELETE changes to MySQL
    db.commit()
    # close cursor after DELETE is done
    cursor.close()

    # return True to controller 
    # to indicate that order was deleted
    return True


def purchase(order_id, user_id):
    # first check whether this order belonggs to current user
    existing_order = get_order_receipt(order_id, user_id)

    if not existing_order:
        return None, "Order does not exist"

    # paid order cannot be paid again
    if existing_order["paid"]:
        return None, "Order is paid already"

    db = get_db()
    cursor = db.cursor()
    # mark only current user's order as paid
    cursor.execute(
        """UPDATE orders 
        SET paid = 1 
        WHERE id = %s AND user_id = %s
        """,
        (order_id, user_id)
    )

    db.commit()
    cursor.close()

    # return updated receipt after payment
    return get_order_receipt(order_id, user_id), None


def get_unpaid_order_by_user_id(user_id):
    db = get_db()
    cursor = db.cursor()

    # find current user's unpaid order
    # it is used to avoid creating a new order before the previous one is paid
    cursor.execute(
        """
        SELECT id FROM orders
        WHERE user_id = %s AND paid = 0
        LIMIT 1
        """,
        (user_id,)
    )

    order = cursor.fetchone()
    cursor.close()

    if order:
        return order["id"]

    return None


# backward-compatible helper for existing code that alreadt passes auth token
# new code should prefer get unpaid_order_by_user_id(user_id) ???
def get_existing_order_id(auth_token):
    db = get_db()
    cursor = db.cursor()
    cursor.execute("""
        SELECT orders.id FROM orders
        JOIN users ON orders.user_id = users.id
        WHERE users.auth_key = %s AND orders.paid = 0
        LIMIT 1
        """,
        (auth_token,)
    )
    order = cursor.fetchone()
    cursor.close()

    if order:
        return order["id"]

    return None