# import the halper function, responsible for opening, 
# providing and safely closing a database connection 
# for each HTTP request
from src.models.database import get_db

def get_all_products():
    # get database connection
    db = get_db()
    # create cursor - is the tool that sends SQL commands to MySQL
    cursor = db.cursor()
    # get all rows from products table
    cursor.execute("SELECT * FROM products")
    # fetchall() returns all rows found by SELECT as a list of dictionaries
    products = cursor.fetchall()
    # close cursor after finishing database work
    cursor.close()

    # return product list to controller
    return products


def get_product_by_id(product_id):
    db = get_db()
    # create cursor to execute SQL connection
    cursor = db.cursor()
    # get one product by id
    # %s is a placeholder; 
    # product_id is passed separetly to avoid SQL injection
    cursor.execute(
        "SELECT * FROM products WHERE id = %s",
        (product_id,)
    )
    # fetchone() returns one row if found 
    # or None if product does not exist
    product = cursor.fetchone()
    # closw cursor after query is done
    cursor.close()

    # return found product or None to controller
    return product


def get_product_by_name(name):
    db = get_db()
    cursor = db.cursor()
    # search products by partial name
    # LIKE with %name% means: 
    # find product names that contain the given text
    cursor.execute(
        "SELECT * FROM products WHERE name LIKE %s",
        (f"%{name}%",)
    )
    # fatchall() returns all matched products as a list
    found_products = cursor.fetchall()
    cursor.close()

    # return matched products to controller
    return found_products


def get_product_by_min_price(price):
    db = get_db()
    cursor = db.cursor()
    # search products where price is greater than or equal to the given price
    cursor.execute("SELECT * FROM products WHERE price >= %s",
    (price,)
    )
    # get all products that match the price condition
    found_products = cursor.fetchall()
    cursor.close()

    # return matched products to controller
    return found_products


def get_product_by_max_price(price):
    db = get_db()
    cursor = db.cursor()
    # search products where price is less than or equal to the given price
    cursor.execute("SELECT * FROM products WHERE price <= %s",
    (price,)
    )
    # get all products that match the given condition
    found_products = cursor.fetchall()
    cursor.close()

    # return matched products to controller
    return found_products


def create_product(name, price, description, stock):
    db = get_db()
    cursor = db.cursor()
    # insert new product into products table 
    # id, created_at and updated_at are handled by MySQL table settings
    cursor.execute(
        "INSERT INTO products (name, price, description, stock) VALUES (%s, %s, %s, %s)",
        (name, price, description, stock)
    )
    # save INSERT changes to MySQL
    db.commit()
    # lastrowid is the id generated by MySQL for the new product
    new_product_id = cursor.lastrowid
    # close cursor after INSERT is done
    cursor.close()

    # return new product ID so controller can fetch and return created product 
    return new_product_id


def update_product(product_id, name, price, description, stock):
    # first check whether the product exists before updating
    product_before_update = get_product_by_id(product_id)

    # if product does not exist, return None to controller
    if not product_before_update:
        return None
    # if name was not provided in request_body, keep old name
    if name is None:
        name = product_before_update["name"]
    # if price was not provided in request_body, keep old price
    if price is None:
        price = product_before_update["price"]
    # if description was not provided in request body, keep old description
    if description is None:
        description = product_before_update["description"]
    # if stock was not provided in request body, keep old stock
    if stock is None:
        stock = product_before_update["stock"]
    
    db = get_db()
    cursor = db.cursor()
    # update only the product with the given ID 
    # WHERE id = %s is important because 
    # without it MySQL would update all product
    cursor.execute(
        """
        UPDATE products
        SET 
            name = %s,
            price = %s,
            description = %s,
            stock = %s
        WHERE id = %s
        """,
        (name, price, description, stock, product_id)
    )
    # save UPDATE changes to MySQL
    db.commit()
    # close cursor after UPDATE is done
    cursor.close()

    # return updated product to controller
    return get_product_by_id(product_id)


def delete_product(product_id):
    # first check whether the product exists before deleting
    desired_product = get_product_by_id(product_id)

    # if product does not exist, return False to controller
    # controller will convert this result to 404 error response
    if not desired_product:
        return False

    db = get_db()
    cursor = db.cursor()
    # delete product from products table by id
    cursor.execute(
        "DELETE FROM products WHERE id = %s",
        (product_id,) 
    )
    # save DELETE changes to MySQL
    db.commit()
    # close cursor after DELETE is done
    cursor.close()

    # return True to controller 
    # to indicate that product was deleted
    return True